name: Tests
on: [ pull_request ]

jobs:
  unit:
    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Download dependencies
        uses: ramsey/composer-install@v3

      - name: PHPUnit
        run: ./vendor/bin/phpunit
